"""auto-generated migration from deployment

Revision ID: 01333ecbb831
Revises: 4297c48213cc
Create Date: 2026-03-17 17:32:22.337219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01333ecbb831'
down_revision = '4297c48213cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
