"""auto-generated migration from deployment

Revision ID: 025aaa5a22de
Revises: ad4b080e08a4
Create Date: 2026-09-13 22:32:56.648352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025aaa5a22de'
down_revision = 'ad4b080e08a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('external_item_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('picked_by', sa.String(length=64), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['external_item_id'], ['external_item.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'external_item_id', name='uq_feed_pick_node_item')
    )
    with op.batch_alter_table('feed_pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_pick_external_item_id'), ['external_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_pick_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_pick_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_pick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_pick_user_id'))
        batch_op.drop_index(batch_op.f('ix_feed_pick_node_id'))
        batch_op.drop_index(batch_op.f('ix_feed_pick_external_item_id'))

    op.drop_table('feed_pick')
    # ### end Alembic commands ###
