"""auto-generated migration from deployment

Revision ID: 02c118dfb8e5
Revises: 2d72971bff0b
Create Date: 2026-07-02 16:26:14.138359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c118dfb8e5'
down_revision = '2d72971bff0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('share_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_draft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_draft_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_draft_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_draft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_draft_status'))
        batch_op.drop_index(batch_op.f('ix_share_draft_created_at'))

    op.drop_table('share_draft')
    # ### end Alembic commands ###
