"""auto-generated migration from deployment

Revision ID: 07405cd35297
Revises: e2e0f22627b0
Create Date: 2025-11-19 13:39:17.916219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07405cd35297'
down_revision = 'e2e0f22627b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('audio_tts_url', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('tts_task_id', sa.String(length=255), nullable=True))
    op.add_column('user_profile', sa.Column('tts_task_status', sa.String(length=20), nullable=True))
    op.add_column('user_profile', sa.Column('tts_task_progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'tts_task_progress')
    op.drop_column('user_profile', 'tts_task_status')
    op.drop_column('user_profile', 'tts_task_id')
    op.drop_column('user_profile', 'audio_tts_url')
    # ### end Alembic commands ###
