"""auto-generated migration from deployment

Revision ID: 0c7843c6ffd3
Revises: 149555c439b6
Create Date: 2026-08-28 23:25:50.684568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7843c6ffd3'
down_revision = '149555c439b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_path', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen_path')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
