"""Add column for timestamp of app terms agreement

Revision ID: 0f5ae6b075c0
Revises: d121c82077bb
Create Date: 2025-03-20 15:37:49.417283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5ae6b075c0'
down_revision = 'd121c82077bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('accepted_terms_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'accepted_terms_at')
    # ### end Alembic commands ###
