"""auto-generated migration from deployment

Revision ID: 18450bbc7081
Revises: e1ecdb34d365
Create Date: 2026-07-03 21:55:07.035847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18450bbc7081'
down_revision = 'e1ecdb34d365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_user_id', sa.String(length=64), nullable=True),
    sa.Column('handle', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_external_account_user_provider')
    )
    with op.batch_alter_table('external_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_account_user_id'), ['user_id'], unique=False)

    op.create_table('external_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('author_handle', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('surfaced_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_surfaced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_external_item_user_source_ext')
    )
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_item_user_id'), ['user_id'], unique=False)

    op.create_table('external_item_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['external_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_item_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_item_embedding_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_item_embedding_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_content_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('external_content_enabled')

    with op.batch_alter_table('external_item_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_item_embedding_user_id'))
        batch_op.drop_index(batch_op.f('ix_external_item_embedding_item_id'))

    op.drop_table('external_item_embedding')
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_item_user_id'))

    op.drop_table('external_item')
    with op.batch_alter_table('external_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_account_user_id'))

    op.drop_table('external_account')
    # ### end Alembic commands ###
