"""auto-generated migration from deployment

Revision ID: 198eb61e987d
Revises: 18450bbc7081
Create Date: 2026-07-06 02:02:18.080432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198eb61e987d'
down_revision = '18450bbc7081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_embedding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_embedding', schema=None) as batch_op:
        batch_op.drop_column('node_updated_at')

    # ### end Alembic commands ###
