"""auto-generated migration from deployment

Revision ID: 1d2700b69cfc
Revises: d6ffd94d9e83
Create Date: 2026-06-02 17:24:11.348873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2700b69cfc'
down_revision = 'd6ffd94d9e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_batch_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_batch_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_batch_job_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_batch_pending', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('profile_batch_attempts', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_batch_attempts')
        batch_op.drop_column('profile_batch_pending')

    with op.batch_alter_table('profile_batch_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_batch_job_batch_id'))

    op.drop_table('profile_batch_job')
    # ### end Alembic commands ###
