"""auto-generated migration from deployment

Revision ID: 1ea5e424af75
Revises: 9f7463384ff8
Create Date: 2026-06-15 14:44:52.730721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea5e424af75'
down_revision = '9f7463384ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('spend_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'month', 'threshold', name='uq_spend_alert_provider_month_threshold')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spend_alert')
    # ### end Alembic commands ###
