"""auto-generated migration from deployment

Revision ID: 2003636a78f5
Revises: 8f4a2e1c9b3d
Create Date: 2026-05-06 22:10:19.816975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2003636a78f5'
down_revision = '8f4a2e1c9b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streaming_mime_type', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_column('streaming_mime_type')

    # ### end Alembic commands ###
