"""auto-generated migration from deployment

Revision ID: 20a83f86ae52
Revises: c87c792e6091
Create Date: 2026-08-27 22:01:25.863992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a83f86ae52'
down_revision = 'c87c792e6091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefill_consent', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('prefill_consent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefill_consent_at')
        batch_op.drop_column('prefill_consent')

    # ### end Alembic commands ###
