"""auto-generated migration from deployment

Revision ID: 24f378332c96
Revises: afc43c8ec0e7
Create Date: 2026-09-18 14:03:19.970677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24f378332c96'
down_revision = 'afc43c8ec0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ai_preferences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('privacy_level', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('ai_usage', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_ai_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_ai_preferences_pkey')
    )
    # ### end Alembic commands ###
