"""auto-generated migration from deployment

Revision ID: 2643bfbe2700
Revises: 97a434e050ec
Create Date: 2026-03-02 16:45:58.174676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2643bfbe2700'
down_revision = '97a434e050ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('human_owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['human_owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('human_owner_id')

    # ### end Alembic commands ###
