"""auto-generated migration from deployment

Revision ID: 27bc59ffad65
Revises: 01333ecbb831
Create Date: 2026-03-19 21:53:54.789754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bc59ffad65'
down_revision = '01333ecbb831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recent_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source_data_cutoff', sa.DateTime(), nullable=True),
    sa.Column('source_tokens_covered', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('ai_usage', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recent_context')
    # ### end Alembic commands ###
