"""auto-generated migration from deployment

Revision ID: 2d72971bff0b
Revises: b27c9eaea993
Create Date: 2026-06-30 16:43:16.484218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d72971bff0b'
down_revision = 'b27c9eaea993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tts_chunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section_title', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tts_chunk', schema=None) as batch_op:
        batch_op.drop_column('section_title')
        batch_op.drop_column('section_index')

    # ### end Alembic commands ###
