"""auto-generated migration from deployment

Revision ID: 31515d579291
Revises: 6ffcb626762f
Create Date: 2026-09-12 11:14:35.055022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31515d579291'
down_revision = '6ffcb626762f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
