"""auto-generated migration from deployment

Revision ID: 33897948f94c
Revises: 51aec2a99de3
Create Date: 2026-09-28 21:50:49.757406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33897948f94c'
down_revision = '51aec2a99de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streaming_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_column('streaming_content')

    # ### end Alembic commands ###
