"""auto-generated migration from deployment

Revision ID: 3724362f2c09
Revises: 54816b0e8135
Create Date: 2025-12-03 22:09:07.282018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3724362f2c09'
down_revision = '54816b0e8135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('privacy_level', sa.String(length=16), nullable=False))
    op.add_column('node', sa.Column('ai_usage', sa.String(length=16), nullable=False))
    op.add_column('user_profile', sa.Column('privacy_level', sa.String(length=16), nullable=False))
    op.add_column('user_profile', sa.Column('ai_usage', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'ai_usage')
    op.drop_column('user_profile', 'privacy_level')
    op.drop_column('node', 'ai_usage')
    op.drop_column('node', 'privacy_level')
    # ### end Alembic commands ###
