"""auto-generated migration from deployment

Revision ID: 3724362f2c09
Revises: 54816b0e8135
Create Date: 2025-12-03 22:09:07.282018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3724362f2c09'
down_revision = '54816b0e8135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to avoid NOT NULL constraint violation on existing rows
    op.add_column('node', sa.Column('privacy_level', sa.String(length=16), nullable=True))
    op.add_column('node', sa.Column('ai_usage', sa.String(length=16), nullable=True))
    op.add_column('user_profile', sa.Column('privacy_level', sa.String(length=16), nullable=True))
    op.add_column('user_profile', sa.Column('ai_usage', sa.String(length=16), nullable=True))

    # Set default values for existing rows
    # Nodes: private + train (maintains training data value proposition)
    op.execute("UPDATE node SET privacy_level = 'private' WHERE privacy_level IS NULL")
    op.execute("UPDATE node SET ai_usage = 'train' WHERE ai_usage IS NULL")

    # User profiles: private + chat (useful for AI responses)
    op.execute("UPDATE user_profile SET privacy_level = 'private' WHERE privacy_level IS NULL")
    op.execute("UPDATE user_profile SET ai_usage = 'chat' WHERE ai_usage IS NULL")

    # Now make columns NOT NULL
    op.alter_column('node', 'privacy_level', nullable=False)
    op.alter_column('node', 'ai_usage', nullable=False)
    op.alter_column('user_profile', 'privacy_level', nullable=False)
    op.alter_column('user_profile', 'ai_usage', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'ai_usage')
    op.drop_column('user_profile', 'privacy_level')
    op.drop_column('node', 'ai_usage')
    op.drop_column('node', 'privacy_level')
    # ### end Alembic commands ###
