"""auto-generated migration from deployment

Revision ID: 3dc014f2f7e6
Revises: da43e268863a
Create Date: 2026-09-04 14:22:15.315199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc014f2f7e6'
down_revision = 'da43e268863a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_token_ratio_family', sa.String(length=16), nullable=True))

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_rendered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('source_rendered_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_token_ratio_family')

    # ### end Alembic commands ###
