"""auto-generated migration from deployment

Revision ID: 3e79674b7753
Revises: 0c7843c6ffd3
Create Date: 2026-08-31 22:52:08.158435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e79674b7753'
down_revision = '0c7843c6ffd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_view_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_view_viewed_at'), ['viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_view_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_artifact_view_user_id'))

    op.drop_table('artifact_view')
    # ### end Alembic commands ###
