"""auto-generated migration from deployment

Revision ID: 40fe548d2a85
Revises: 24f378332c96
Create Date: 2026-09-18 14:49:59.280721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fe548d2a85'
down_revision = '24f378332c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('username_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_username', sa.String(length=64), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('username_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_username_history_old_username'), ['old_username'], unique=True)
        batch_op.create_index(batch_op.f('ix_username_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('username_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_username_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_username_history_old_username'))

    op.drop_table('username_history')
    # ### end Alembic commands ###
