"""auto-generated migration from deployment

Revision ID: 4297c48213cc
Revises: a1c2e3f4g5h6
Create Date: 2026-03-17 12:42:10.636760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4297c48213cc'
down_revision = 'a1c2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_constraint('node_user_prompt_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_prompt_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_prompt_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('node_user_prompt_id_fkey', 'user_prompt', ['user_prompt_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
