"""auto-generated migration from deployment

Revision ID: 456ad05178db
Revises: ba0218822d75
Create Date: 2026-04-26 15:21:45.927567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456ad05178db'
down_revision = 'ba0218822d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streaming_warning', sa.Text(), nullable=True))

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_task_warnings', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_column('llm_task_warnings')

    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_column('streaming_warning')

    # ### end Alembic commands ###
