"""auto-generated migration from deployment

Revision ID: 507585cd6ba6
Revises: 9dfc6fa1fa5c
Create Date: 2026-06-24 16:28:23.447028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507585cd6ba6'
down_revision = '9dfc6fa1fa5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_embedding_node_id'), ['node_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_node_embedding_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_embedding_user_id'))
        batch_op.drop_index(batch_op.f('ix_node_embedding_node_id'))

    op.drop_table('node_embedding')
    # ### end Alembic commands ###
