"""auto-generated migration from deployment

Revision ID: 51aec2a99de3
Revises: 649744f8f109
Create Date: 2026-09-24 22:15:40.701765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51aec2a99de3'
down_revision = '649744f8f109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_cost_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_response_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('cache_diag_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('cache_diag_reason', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('cache_diag_reusable_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache_diag_missed_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache_diag_baseline', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('cache_diag_gap_s', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('system_prefix_hash', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_cost_log_request_ref'), ['request_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_cost_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cost_log_request_ref'))
        batch_op.drop_column('system_prefix_hash')
        batch_op.drop_column('cache_diag_gap_s')
        batch_op.drop_column('cache_diag_baseline')
        batch_op.drop_column('cache_diag_missed_tokens')
        batch_op.drop_column('cache_diag_reusable_tokens')
        batch_op.drop_column('cache_diag_reason')
        batch_op.drop_column('cache_diag_type')
        batch_op.drop_column('provider_response_id')

    # ### end Alembic commands ###
