"""auto-generated migration from deployment

Revision ID: 649744f8f109
Revises: 6fca8c47bd7d
Create Date: 2026-09-24 20:19:09.801667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649744f8f109'
down_revision = '6fca8c47bd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('value', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['external_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_action_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_action_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_action_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('feed_pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=8), server_default='read', nullable=False))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prior_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prior_verdict', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_pick', schema=None) as batch_op:
        batch_op.drop_column('prior_verdict')
        batch_op.drop_column('prior_read')
        batch_op.drop_column('decided_at')
        batch_op.drop_column('kind')

    with op.batch_alter_table('reference_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_action_user_id'))
        batch_op.drop_index(batch_op.f('ix_reference_action_node_id'))
        batch_op.drop_index(batch_op.f('ix_reference_action_item_id'))

    op.drop_table('reference_action')
    # ### end Alembic commands ###
