"""auto-generated migration from deployment

Revision ID: 67115802ded4
Revises: 33897948f94c
Create Date: 2026-10-01 13:18:04.683056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67115802ded4'
down_revision = '33897948f94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streaming_heartbeat_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('external_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_incomplete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.drop_column('saved_at')

    with op.batch_alter_table('external_account', schema=None) as batch_op:
        batch_op.drop_column('sync_incomplete')

    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_column('streaming_heartbeat_at')

    # ### end Alembic commands ###
