"""auto-generated migration from deployment

Revision ID: 6fca8c47bd7d
Revises: f441ed6a1156
Create Date: 2026-09-23 14:28:40.406566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fca8c47bd7d'
down_revision = 'f441ed6a1156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_handle', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('x_connected_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('x_connected_at')
        batch_op.drop_column('twitter_handle')

    # ### end Alembic commands ###
