"""auto-generated migration from deployment

Revision ID: 7156f689546b
Revises: d2280bbc4899
Create Date: 2026-08-27 16:18:06.480405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7156f689546b'
down_revision = 'd2280bbc4899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_force_batch', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('profile_token_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prefilled_handle', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefilled_handle')
        batch_op.drop_column('profile_token_ratio')
        batch_op.drop_column('profile_force_batch')

    # ### end Alembic commands ###
