"""auto-generated migration from deployment

Revision ID: 7e4d49d8dc7b
Revises: a8ea77c51992
Create Date: 2026-01-15 23:37:49.049045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4d49d8dc7b'
down_revision = 'a8ea77c51992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('streaming_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('streaming_total_chunks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streaming_completed_chunks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('privacy_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_usage', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_draft_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('node_transcript_chunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_node_transcript_chunk_session_id'), ['session_id'], unique=False)
        batch_op.create_unique_constraint('uq_session_chunk_index', ['session_id', 'chunk_index'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_transcript_chunk', schema=None) as batch_op:
        batch_op.drop_constraint('uq_session_chunk_index', type_='unique')
        batch_op.drop_index(batch_op.f('ix_node_transcript_chunk_session_id'))
        batch_op.alter_column('node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('session_id')

    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_session_id'))
        batch_op.drop_column('ai_usage')
        batch_op.drop_column('privacy_level')
        batch_op.drop_column('streaming_completed_chunks')
        batch_op.drop_column('streaming_total_chunks')
        batch_op.drop_column('streaming_status')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
