"""auto-generated migration from deployment

Revision ID: 833ce6a5b6ab
Revises: 2643bfbe2700
Create Date: 2026-03-03 22:14:50.692133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833ce6a5b6ab'
down_revision = '2643bfbe2700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_prompt_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user_prompt', ['user_prompt_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('user_prompt_id')

    # ### end Alembic commands ###
