"""add deleted_at to node (with CONCURRENTLY index)

Revision ID: 8f4a2e1c9b3d
Revises: 456ad05178db
Create Date: 2026-05-05 00:00:00.000000

This migration is **pre-committed manually** rather than auto-generated by
the deploy script. It uses ``CREATE INDEX CONCURRENTLY`` (via Alembic's
``autocommit_block``) so the index build doesn't lock writes against the
populated ``node`` table during deploy. The auto-generated equivalent
would emit a plain ``CREATE INDEX`` and stall production writes briefly.

If you change ``Node.deleted_at`` later, that change CAN be auto-generated
as usual — the override here is a one-time exception for the initial
index build.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4a2e1c9b3d'
down_revision = '456ad05178db'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column inside the standard transactional DDL block.
    op.add_column(
        'node',
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
    )

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction —
    # autocommit_block exits the surrounding transaction so the
    # statement runs on its own.
    with op.get_context().autocommit_block():
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_node_deleted_at "
            "ON node (deleted_at)"
        )


def downgrade():
    with op.get_context().autocommit_block():
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS ix_node_deleted_at")

    op.drop_column('node', 'deleted_at')
