"""auto-generated migration from deployment

Revision ID: 94752f1a97d7
Revises: 31515d579291
Create Date: 2026-09-12 11:47:29.983087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94752f1a97d7'
down_revision = '31515d579291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_created', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_account', schema=None) as batch_op:
        batch_op.drop_column('last_sync_created')

    # ### end Alembic commands ###
