"""Add column for admin rights

Revision ID: 95f685265129
Revises: c68160c673f5
Create Date: 2025-04-22 19:20:50.227136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f685265129'
down_revision = 'c68160c673f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('audio_original_url', sa.String(), nullable=True))
    op.add_column('node', sa.Column('audio_tts_url', sa.String(), nullable=True))
    op.add_column('node', sa.Column('audio_duration_sec', sa.Float(), nullable=True))
    op.add_column('node', sa.Column('audio_mime_type', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('plan', sa.String(length=16), nullable=False, server_default="free"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'plan')
    op.drop_column('user', 'is_admin')
    op.drop_column('node', 'audio_mime_type')
    op.drop_column('node', 'audio_duration_sec')
    op.drop_column('node', 'audio_tts_url')
    op.drop_column('node', 'audio_original_url')
    # ### end Alembic commands ###
