"""auto-generated migration from deployment

Revision ID: 97704b787610
Revises: 7791feaf755a
Create Date: 2026-02-20 23:30:02.278688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97704b787610'
down_revision = '7791feaf755a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_model', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_model')

    # ### end Alembic commands ###
