"""auto-generated migration from deployment

Revision ID: 97a434e050ec
Revises: b77a55814bb4
Create Date: 2026-02-26 23:38:14.600621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a434e050ec'
down_revision = 'b77a55814bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_generation_task_dispatched_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_generation_task_dispatched_at')

    # ### end Alembic commands ###
