"""auto-generated migration from deployment

Revision ID: 9cec32f840d0
Revises: 94752f1a97d7
Create Date: 2026-09-12 16:28:26.327784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cec32f840d0'
down_revision = '94752f1a97d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_digest_batch_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_digest_batch_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_digest_batch_job_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_digest_batch_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_digest_batch_job_batch_id'))

    op.drop_table('external_digest_batch_job')
    # ### end Alembic commands ###
