"""auto-generated migration from deployment

Revision ID: 9dfc6fa1fa5c
Revises: d33dd2c82706
Create Date: 2026-06-24 14:56:04.049682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfc6fa1fa5c'
down_revision = 'd33dd2c82706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_spend_limit_usd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monthly_spend_limit_usd')

    # ### end Alembic commands ###
