"""auto-generated migration from deployment

Revision ID: 9f7463384ff8
Revises: 1d2700b69cfc
Create Date: 2026-06-10 22:28:05.416464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7463384ff8'
down_revision = '1d2700b69cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_key', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_node_source_key'), ['source_key'], unique=False)
        batch_op.create_unique_constraint('uq_node_human_owner_source_key', ['human_owner_id', 'source_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_constraint('uq_node_human_owner_source_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_node_source_key'))
        batch_op.drop_column('source_key')

    # ### end Alembic commands ###
