"""auto-generated migration from deployment

Revision ID: a1b6e79d6356
Revises: 02c118dfb8e5
Create Date: 2026-07-02 16:30:46.000523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b6e79d6356'
down_revision = '02c118dfb8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_slug', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_node_public_slug'), ['public_slug'], unique=False)

    with op.batch_alter_table('share_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'node', ['public_node_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_sharing_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('public_sharing_enabled')

    with op.batch_alter_table('share_draft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('public_node_id')

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_public_slug'))
        batch_op.drop_column('public_slug')

    # ### end Alembic commands ###
