"""auto-generated migration from deployment

Revision ID: a8ea77c51992
Revises: 3724362f2c09
Create Date: 2026-01-15 21:01:57.751697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ea77c51992'
down_revision = '3724362f2c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_transcript_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'chunk_index', name='uq_node_chunk_index')
    )
    op.create_table('tts_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'chunk_index', name='uq_node_tts_chunk_index')
    )
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streaming_transcription', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('streaming_total_chunks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streaming_completed_chunks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streaming_session_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_column('streaming_session_id')
        batch_op.drop_column('streaming_completed_chunks')
        batch_op.drop_column('streaming_total_chunks')
        batch_op.drop_column('streaming_transcription')

    op.drop_table('tts_chunk')
    op.drop_table('node_transcript_chunk')
    # ### end Alembic commands ###
