"""auto-generated migration from deployment

Revision ID: ad4b080e08a4
Revises: cd46311bc2eb
Create Date: 2026-09-12 22:27:28.672563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4b080e08a4'
down_revision = 'cd46311bc2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('feedback_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.drop_column('feedback_at')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
