"""auto-generated migration from deployment

Revision ID: afc43c8ec0e7
Revises: b4373d0fb625
Create Date: 2026-09-18 11:34:40.610756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc43c8ec0e7'
down_revision = 'b4373d0fb625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_change_token_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_change_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_change_expires_at')
        batch_op.drop_column('email_change_token_hash')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
