"""auto-generated migration from deployment

Revision ID: b27c9eaea993
Revises: 507585cd6ba6
Create Date: 2026-06-25 13:58:23.020773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27c9eaea993'
down_revision = '507585cd6ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_cost_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cache_read_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache_write_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_cost_log', schema=None) as batch_op:
        batch_op.drop_column('cache_write_tokens')
        batch_op.drop_column('cache_read_tokens')

    # ### end Alembic commands ###
