"""auto-generated migration from deployment

Revision ID: b4373d0fb625
Revises: 025aaa5a22de
Create Date: 2026-09-15 08:59:35.493076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4373d0fb625'
down_revision = '025aaa5a22de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_seed_error', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_seed_error')

    # ### end Alembic commands ###
