"""auto-generated migration from deployment

Revision ID: b77a55814bb4
Revises: 97704b787610
Create Date: 2026-02-24 23:17:22.958256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77a55814bb4'
down_revision = '97704b787610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('based_on_default_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_prompt', schema=None) as batch_op:
        batch_op.drop_column('based_on_default_hash')

    # ### end Alembic commands ###
