"""auto-generated migration from deployment

Revision ID: ba0218822d75
Revises: c7d0543b4998
Create Date: 2026-03-31 13:54:46.969654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0218822d75'
down_revision = 'c7d0543b4998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.alter_column('token_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.alter_column('token_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
