"""Add column for whitelisting for limited alpha release

Revision ID: c68160c673f5
Revises: 0f5ae6b075c0
Create Date: 2025-03-20 16:53:01.458611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68160c673f5'
down_revision = '0f5ae6b075c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('approved', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('user', 'approved')
    # ### end Alembic commands ###
