"""auto-generated migration from deployment

Revision ID: c69e5dba4e83
Revises: 67115802ded4
Create Date: 2026-10-08 13:01:33.530926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69e5dba4e83'
down_revision = '67115802ded4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_context_batch_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recent_context_batch_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_context_batch_job_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recent_context_batch_job_collected_at'), ['collected_at'], unique=False)

    with op.batch_alter_table('feed_render', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropped_picks', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('opened_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_render', schema=None) as batch_op:
        batch_op.drop_column('opened_at')
        batch_op.drop_column('dropped_picks')

    with op.batch_alter_table('recent_context_batch_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_context_batch_job_collected_at'))
        batch_op.drop_index(batch_op.f('ix_recent_context_batch_job_batch_id'))

    op.drop_table('recent_context_batch_job')
    # ### end Alembic commands ###
