"""auto-generated migration from deployment

Revision ID: c7d0543b4998
Revises: 27bc59ffad65
Create Date: 2026-03-25 21:06:13.255004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d0543b4998'
down_revision = '27bc59ffad65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_level', sa.String(length=16), nullable=False),
    sa.Column('ai_usage', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_calls_meta', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_column('tool_calls_meta')

    op.drop_table('user_ai_preferences')
    # ### end Alembic commands ###
