"""auto-generated migration from deployment

Revision ID: c87c792e6091
Revises: 7156f689546b
Create Date: 2026-08-27 18:19:27.742210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87c792e6091'
down_revision = '7156f689546b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_human_owner_id'), ['human_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_user_id'))
        batch_op.drop_index(batch_op.f('ix_node_parent_id'))
        batch_op.drop_index(batch_op.f('ix_node_human_owner_id'))

    # ### end Alembic commands ###
