"""auto-generated migration from deployment

Revision ID: cd46311bc2eb
Revises: 9cec32f840d0
Create Date: 2026-09-12 17:28:33.570397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd46311bc2eb'
down_revision = '9cec32f840d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('audio_tts_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tts_task_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tts_task_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tts_task_progress', sa.Integer(), nullable=True))

    with op.batch_alter_table('tts_chunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_item_tts_chunk_index', ['item_id', 'chunk_index'])
        batch_op.create_foreign_key(None, 'external_item', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tts_chunk', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_item_tts_chunk_index', type_='unique')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.drop_column('tts_task_progress')
        batch_op.drop_column('tts_task_status')
        batch_op.drop_column('tts_task_id')
        batch_op.drop_column('audio_tts_url')
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###
