"""Add distributed_tokens

Revision ID: d121c82077bb
Revises: 0da779a03866
Create Date: 2025-03-17 15:41:44.720136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd121c82077bb'
down_revision = '0da779a03866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('distributed_tokens', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'distributed_tokens')
    # ### end Alembic commands ###
