"""auto-generated migration from deployment

Revision ID: d2280bbc4899
Revises: 198eb61e987d
Create Date: 2026-08-27 11:37:16.168906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2280bbc4899'
down_revision = '198eb61e987d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_node_origin'), ['origin'], unique=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_origin_stats', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('source_origin_stats')

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_origin'))
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
