"""user artifacts (#158)

Revision ID: d33dd2c82706
Revises: b7c8d9e0f1a2
Create Date: 2026-06-17 17:42:15.318769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33dd2c82706'
down_revision = 'b7c8d9e0f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_level', sa.String(length=16), nullable=False),
    sa.Column('ai_usage', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_artifact_kind'), ['kind'], unique=False)

    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continuation_node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'node', ['continuation_node_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('continuation_node_id')

    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_created_at'))

    op.drop_table('user_feedback')
    with op.batch_alter_table('user_artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_artifact_kind'))

    op.drop_table('user_artifact')
    # ### end Alembic commands ###
