"""auto-generated migration from deployment

Revision ID: da43e268863a
Revises: 3e79674b7753
Create Date: 2026-09-02 15:52:14.773922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da43e268863a'
down_revision = '3e79674b7753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_column('prompt_key')

    # ### end Alembic commands ###
