"""auto-generated migration from deployment

Revision ID: e1ecdb34d365
Revises: a1b6e79d6356
Create Date: 2026-07-03 12:27:19.892445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ecdb34d365'
down_revision = 'a1b6e79d6356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_draft_batch_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_draft_batch_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_draft_batch_job_batch_id'), ['batch_id'], unique=False)

    op.create_table('changelog_read_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_changelog_read_user_section')
    )
    with op.batch_alter_table('changelog_read_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changelog_read_state_user_id'), ['user_id'], unique=False)

    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('data_source', sa.String(length=16), server_default='derived', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_created_at'), ['created_at'], unique=False)

    op.create_table('user_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('skipped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_user_id'), ['user_id'], unique=False)

    op.create_table('poll_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=True),
    sa.Column('draft_task_id', sa.String(length=255), nullable=True),
    sa.Column('draft_requested_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_response_poll_user')
    )
    with op.batch_alter_table('poll_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_response_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_response_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_response_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('api_cost_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_ref', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_cost_log', schema=None) as batch_op:
        batch_op.drop_column('request_ref')

    with op.batch_alter_table('poll_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_response_user_id'))
        batch_op.drop_index(batch_op.f('ix_poll_response_status'))
        batch_op.drop_index(batch_op.f('ix_poll_response_poll_id'))

    op.drop_table('poll_response')
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_notification_status'))
        batch_op.drop_index(batch_op.f('ix_user_notification_created_at'))

    op.drop_table('user_notification')
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_created_at'))

    op.drop_table('poll')
    with op.batch_alter_table('changelog_read_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changelog_read_state_user_id'))

    op.drop_table('changelog_read_state')
    with op.batch_alter_table('poll_draft_batch_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_draft_batch_job_batch_id'))

    op.drop_table('poll_draft_batch_job')
    # ### end Alembic commands ###
