"""auto-generated migration from deployment

Revision ID: e2e0ab2f118a
Revises: 40fe548d2a85
Create Date: 2026-09-21 18:35:10.941185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e0ab2f118a'
down_revision = '40fe548d2a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_render',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('export_id', sa.String(length=64), nullable=True),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('tweet_count', sa.Integer(), nullable=False),
    sa.Column('account_count', sa.Integer(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.Column('tweet_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_render')
    # ### end Alembic commands ###
