"""auto-generated migration from deployment

Revision ID: ed06445e342b
Revises: feecbf6ce3c4
Create Date: 2026-03-12 15:56:43.956490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed06445e342b'
down_revision = 'feecbf6ce3c4'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns as nullable first, backfill existing rows, then set NOT NULL.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_privacy_level', sa.String(length=16), nullable=True, server_default='private'))
        batch_op.add_column(sa.Column('default_ai_usage', sa.String(length=16), nullable=True, server_default='chat'))

    # Backfill any rows that didn't get the server_default (safety net)
    op.execute("UPDATE \"user\" SET default_privacy_level = 'private' WHERE default_privacy_level IS NULL")
    op.execute("UPDATE \"user\" SET default_ai_usage = 'chat' WHERE default_ai_usage IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('default_privacy_level', nullable=False)
        batch_op.alter_column('default_ai_usage', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('default_ai_usage')
        batch_op.drop_column('default_privacy_level')

    # ### end Alembic commands ###
