"""auto-generated migration from deployment

Revision ID: f02da2d8a127
Revises: 1ea5e424af75
Create Date: 2026-06-15 17:47:50.512125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02da2d8a127'
down_revision = '1ea5e424af75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spend_blocked_month', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('spend_blocked_month')

    # ### end Alembic commands ###
