"""auto-generated migration from deployment

Revision ID: f441ed6a1156
Revises: e2e0ab2f118a
Create Date: 2026-09-21 19:27:06.948446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f441ed6a1156'
down_revision = 'e2e0ab2f118a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_source', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('public_source_checked_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provenance', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_column('provenance')

    with op.batch_alter_table('external_item', schema=None) as batch_op:
        batch_op.drop_column('public_source_checked_at')
        batch_op.drop_column('public_source')

    # ### end Alembic commands ###
