"""auto-generated migration from deployment

Revision ID: feecbf6ce3c4
Revises: 833ce6a5b6ab
Create Date: 2026-03-05 13:41:46.213652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feecbf6ce3c4'
down_revision = '833ce6a5b6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_node_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'node', ['llm_node_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('llm_node_id')

    # ### end Alembic commands ###
